apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app.kubernetes.io/part-of: bosun-e2e-deps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
        app.kubernetes.io/part-of: bosun-e2e-deps
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app.kubernetes.io/part-of: bosun-e2e-deps
spec:
  selector:
    app: redis
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-indexing
  labels:
    app.kubernetes.io/part-of: bosun-e2e-deps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-indexing
  template:
    metadata:
      labels:
        app: redis-indexing
        app.kubernetes.io/part-of: bosun-e2e-deps
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-indexing
  labels:
    app.kubernetes.io/part-of: bosun-e2e-deps
spec:
  selector:
    app: redis-indexing
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qdrant
  labels:
    app.kubernetes.io/part-of: bosun-e2e-deps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qdrant
  template:
    metadata:
      labels:
        app: qdrant
        app.kubernetes.io/part-of: bosun-e2e-deps
    spec:
      containers:
        - name: qdrant
          image: qdrant/qdrant:v1.8.4
          ports:
            - containerPort: 6333
            - containerPort: 6334
---
apiVersion: v1
kind: Service
metadata:
  name: qdrant
  labels:
    app.kubernetes.io/part-of: bosun-e2e-deps
spec:
  selector:
    app: qdrant
  ports:
    - name: grpc
      port: 6334
      targetPort: 6334
    - name: http
      port: 6333
      targetPort: 6333
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app.kubernetes.io/part-of: bosun-e2e-deps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
        app.kubernetes.io/part-of: bosun-e2e-deps
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          env:
            - name: POSTGRES_USER
              value: user
            - name: POSTGRES_PASSWORD
              value: pass
            - name: POSTGRES_DB
              value: app
          ports:
            - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app.kubernetes.io/part-of: bosun-e2e-deps
spec:
  selector:
    app: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
